package com.riverdance.ExchangeRateTracker.enumeration;

public enum CurrencyAbbreviation {
    AED("United Arab Emirates Dirham"),
    AFN("Afghan Afghani"),
    ALL("Albanian Lek"),
    AMD("Armenian Dram"),
    ANG("Netherlands Antillean Gulden"),
    AOA("Angolan Kwanza"),
    ARS("Argentine Peso"),
    AUD("Australian Dollar"),
    AWG("Aruban Florin"),
    AZN("Azerbaijani Manat"),
    BAM("Bosnia and Herzegovina Convertible Mark"),
    BBD("Barbadian Dollar"),
    BDT("Bangladeshi Taka"),
    BGN("Bulgarian Lev"),
    BHD("Bahraini Dinar"),
    BIF("Burundian Franc"),
    BMD("Bermudian Dollar"),
    BND("Brunei Dollar"),
    BOB("Bolivian Boliviano"),
    BRL("Real"),
    BSD("Bahamian Dollar"),
    BTN("Bhutanese Ngultrum"),
    BWP("Botswana Pula"),
    BYN("Belarusian Ruble"),
    BYR("Belarusian Ruble"),
    BZD("Belize Dollar"),
    CAD("Canadian Dollar"),
    CDF("Congolese Franc"),
    CHF("Swiss Franc"),
    CLF("Unidad de Fomento"),
    CLP("Chilean Peso"),
    CNY("Chinese Renminbi Yuan"),
    COP("Colombian Peso"),
    CRC("Costa Rican Colón"),
    CUC("Cuban Convertible Peso"),
    CUP("Cuban Peso"),
    CVE("Cape Verdean Escudo"),
    CZK("Czech Koruna"),
    DJF("Djiboutian Franc"),
    DKK("Danish Krone"),
    DOP("Dominican Peso"),
    DZD("Algerian Dinar"),
    EGP("Egyptian Pound"),
    ETB("Ethiopian Birr"),
    EUR("Euro"),
    FJD("Fijian Dollar"),
    FKP("Falkland Pound"),
    GBP("British Pound"),
    GEL("Georgian Lari"),
    GHS("Ghanaian Cedi"),
    GIP("Gibraltar Pound"),
    GMD("Gambian Dalasi"),
    GNF("Guinean Franc"),
    GTQ("Guatemalan Quetzal"),
    GYD("Guyanese Dollar"),
    HKD("Hong Kong Dollar"),
    HNL("Honduran Lempira"),
    HRK("Croatian Kuna"),
    HTG("Haitian Gourde"),
    HUF("Hungarian Forint"),
    IDR("Indonesian Rupiah"),
    ILS("Israeli New Sheqel"),
    INR("Indian Rupee"),
    IQD("Iraqi Dinar"),
    IRR("Iranian Rial"),
    ISK("Icelandic Króna"),
    JMD("Jamaican Dollar"),
    JOD("Jordanian Dinar"),
    JPY("Japanese Yen"),
    KES("Kenyan Shilling"),
    KGS("Kyrgyzstani Som"),
    KHR("Cambodian Riel"),
    KMF("Comorian Franc"),
    KPW("North Korean Won"),
    KRW("South Korean Won"),
    KWD("Kuwaiti Dinar"),
    KYD("Cayman Islands Dollar"),
    KZT("Kazakhstani Tenge"),
    LAK("Lao Kip"),
    LBP("Lebanese Pound"),
    LKR("Sri Lankan Rupee"),
    LRD("Liberian Dollar"),
    LSL("Lesotho Loti"),
    LYD("Libyan Dinar"),
    MAD("Moroccan Dirham"),
    MDL("Moldovan Leu"),
    MGA("Malagasy Ariary"),
    MKD("Macedonian Denar"),
    MMK("Myanmar Kyat"),
    MNT("Mongolian Tögrög"),
    MOP("Macanese Pataca"),
    MRU("Mauritanian Ouguiya"),
    MUR("Mauritian Rupee"),
    MVR("Maldivian Rufiyaa"),
    MWK("Malawian Kwacha"),
    MXN("Mexican Peso"),
    MYR("Malaysian Ringgit"),
    MZN("Mozambican Metical"),
    NAD("Namibian Dollar"),
    NGN("Nigerian Naira"),
    NIO("Nicaraguan Córdoba"),
    NOK("Norwegian Krone"),
    NPR("Nepalese Rupee"),
    NZD("New Zealand Dollar"),
    OMR("Omani Rial"),
    PAB("Panamanian Balboa"),
    PEN("Peruvian Sol"),
    PGK("Papua New Guinean Kina"),
    PHP("Philippine Peso"),
    PKR("Pakistani Rupee"),
    PLN("Polish Złoty"),
    PYG("Paraguayan Guaraní"),
    QAR("Qatari Riyal"),
    RON("Romanian Leu"),
    RSD("Serbian Dinar"),
    RUB("Russian Ruble"),
    RWF("Rwandan Franc"),
    SAR("Saudi Riyal"),
    SBD("Solomon Islands Dollar"),
    SCR("Seychellois Rupee"),
    SDG("Sudanese Pound"),
    SEK("Swedish Krona"),
    SGD("Singapore Dollar"),
    SHP("Saint Helenian Pound"),
    SKK("Slovak Koruna"),
    SLL("Sierra Leonean Leone"),
    SOS("Somali Shilling"),
    SRD("Surinamese Dollar"),
    SSP("South Sudanese Pound"),
    STD("São Tomé and Príncipe Dobra"),
    SVC("Salvadoran Colón"),
    SYP("Syrian Pound"),
    SZL("Swazi Lilangeni"),
    THB("Thai Baht"),
    TJS("Tajikistani Somoni"),
    TMT("Turkmenistani Manat"),
    TND("Tunisian Dinar"),
    TOP("Tongan Paʻanga"),
    TRY("Turkish Lira"),
    TTD("Trinidad and Tobago Dollar"),
    TWD("New Taiwan Dollar"),
    TZS("Tanzanian Shilling"),
    UAH("Ukrainian Hryvnia"),
    UGX("Ugandan Shilling"),
    USD("United States Dollar"),
    UYU("Uruguayan Peso"),
    UZS("Uzbekistan Som"),
    VES("Venezuelan Bolívar Soberano"),
    VND("Vietnamese Đồng"),
    VUV("Vanuatu Vatu"),
    WST("Samoan Tala"),
    XAF("Central African Cfa Franc"),
    XAG("Silver (Troy Ounce)"),
    XAU("Gold (Troy Ounce)"),
    XCD("East Caribbean Dollar"),
    XDR("Special Drawing Rights"),
    XOF("West African Cfa Franc"),
    XPD("Palladium"),
    XPF("Cfp Franc"),
    XPT("Platinum"),
    YER("Yemeni Rial"),
    ZAR("South African Rand"),
    ZMK("Zambian Kwacha"),
    ZMW("Zambian Kwacha"),
    EEK("Estonian Kroon"),
    LTL("Lithuanian Litas"),
    LVL("Latvian Lats"),
    MRO("Mauritanian Ouguiya"),
    TMM("Turkmenistani Manat"),
    ZWD("Zimbabwean Dollar"),
    VEF("Venezuelan Bolívar"),
    JEP("Jersey Pound"),
    GGP("Guernsey Pound"),
    IMP("Isle of Man Pound"),
    CNH("Chinese Renminbi Yuan Offshore");

    private final String countryName;

    CurrencyAbbreviation(String countryName) {
        this.countryName = countryName;
    }

    public String getCountryName() {
        return countryName;
    }
}

